/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'

declare const self: ServiceWorkerGlobalScope

/* ---------------------------------------------------------------------------
   Custom service worker.

   Previously this was generated by workbox. Push notifications need handlers
   the generator cannot produce, so the precaching half is now assembled by
   hand and the push half added alongside it.
   --------------------------------------------------------------------------- */

// __WB_MANIFEST is replaced at build time with the precache list.
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// Single-page app: every navigation resolves to the shell.
registerRoute(new NavigationRoute(createHandlerBoundToURL('/index.html')))

function createHandlerBoundToURL(url: string) {
  return async () => {
    const cache = await caches.open('workbox-precache-v2')
    const match = await cache.match(new URL(url, self.location.origin).href)
    return match ?? fetch(url)
  }
}

// Take over immediately rather than waiting for every window to close — an
// installed PWA is rarely fully closed, which used to leave devices on a stale
// bundle after each deploy.
self.skipWaiting()
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

/* --- push ------------------------------------------------------------------ */

interface PushBody {
  title?: string
  body?: string
  tag?: string
  url?: string
}

self.addEventListener('push', (event) => {
  let data: PushBody = {}
  try {
    data = event.data?.json() ?? {}
  } catch {
    data = { body: event.data?.text() }
  }

  const title = data.title ?? 'Tally'
  event.waitUntil(
    self.registration.showNotification(title, {
      body: data.body ?? 'You have habits left to log today.',
      icon: '/icons/icon-192.png',
      badge: '/icons/icon-192.png',
      // A stable tag means a later reminder replaces the earlier one instead of
      // stacking nine notifications on the lock screen by bedtime.
      tag: data.tag ?? 'habit-reminder',
      renotify: true,
      data: { url: data.url ?? '/' },
    } as NotificationOptions),
  )
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const target = (event.notification.data as { url?: string } | undefined)?.url ?? '/'

  event.waitUntil(
    (async () => {
      const all = await self.clients.matchAll({ type: 'window', includeUncontrolled: true })
      // Focus an open window if there is one, rather than opening a second copy.
      for (const client of all) {
        if ('focus' in client) {
          await client.focus()
          return
        }
      }
      await self.clients.openWindow(target)
    })(),
  )
})
